### ISSUE TITLE
[Question] What is the best plan for task fusion

### ISSUE THREAD

**Issue by rjzamora** [mrocklin/dask-match#9]
Dask-match certainly makes most high-level optimizations simpler than they would be with Dask's current HLG design. However, it is not yet clear to me how task fusion should come into play. There seem to be three general paths forward:

1. We do nothing about task fusion on the expression side.  Instead, we rely on the scheduler to either perform low-level fusion, or to use something like speculative task assignment.
2. We implement a new mechanism within `dask-match` to enable the fusion of "blockwise" parent and child expressions.
3. We modify the "blockwise" `_layer` methods to output `Blockwise` HLG layers instead of low-level dictionaries.

I like that (1) allows use to keep the logic in `dask-match` a bit simpler, but I'm not very confident that this approach will deliver the same benefits as (2) or (3). (3) is clearly the "fastest" way to support task fusion, but we will eventually need to migrate the necessary subgraph-callable logic into the `Expr` version of `Blockwise` if the long-term plan is to scrap HLGs altogether.

**Comment by mrocklin** [comment]
My goal is for low level task fusion goes away entirely

I think that we should implement high level blockwise fusion at the expression layer (not using the HLG Blockwise implementation).  I think that this will likely look very different for arrays and dataframes, and so should hopefully be much simpler if we implement it just once for dataframes, and leave arrays for some other future implementation.

**Comment by rjzamora** [comment]
I started playing around with a possible solution in https://github.com/mrocklin/dask-match/pull/11

It was pretty easy to implement fusion for Blockwise, but my interest in capturing IO expressions made things a bit trickier.

**Comment by mrocklin** [comment]
> I started playing around with a possible solution in https://github.com/mrocklin/dask-match/pull/11

Cool.  Looking now

> It was pretty easy to implement fusion for Blockwise, but my interest in capturing IO expressions made things a bit trickier

I'm curious, with task queuing maybe this isn't as important any longer?

**Comment by rjzamora** [comment]
>I'm curious, with task queuing maybe this isn't as important any longer?

Right - I doubt it replaces fusion completely, but I'm sure fusion is less important if the scheduler can be sure to place the IO task on the same worker as the Blockwise task that depends on it.  That said, it isn't *that* tricky to make these tasks fusable.  We just need a mechanism (like `MappedArg`) to allow us to construct a `SubgraphCallable`-based graph with partition-dependent inputs. This is similar to the `BlockwiseDep` concept in main-line dask.
